# Site settings
title: One - Liners
header-img: img/home-bg.png
email: dapawn@gmail.com
copyright_name: dapawn
description: > # this means to ignore newlines until "baseurl:"
  Clear Concise Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dapawn
learn_profile: dapawn
email_username: dapawn@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
